bundler_args: --without development --path vendor/bundle
script: "bundle exec rake db:drop db:create db:migrate spec"
rvm:
  - 2.1.0
gemfile:
  - Gemfile
branches:
  only:
    - master
env:
  - DB=mysql
